version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  deploy-prod:
    working_directory: ~/repo

    docker:
      - image: circleci/node:10.14.2-stretch
    environment:
      API_URL: http://measles-api-dev.us-west-1.elasticbeanstalk.com

    steps:
      - checkout

      - run:
          name: install deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev g++ build-essential
            sudo pip3 install --upgrade setuptools pytz
            sudo pip3 install awsebcli==3.20.0

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: npm build dash
          command: cd dash; npm install

      - run:
          name: deploy
          command: cd dash; npm run deploy

      - run:
          name: invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
            --distribution-id E39BLBIF64P4WL \
            --paths "/*"

      - run:
          name: Notify Slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{"text":"http://measles-tracker.s3-website-us-west-1.amazonaws.com"}' \
            https://hooks.slack.com/services/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

  deploy-dev:
    working_directory: ~/repo

    docker:
      - image: circleci/node:10.14.2-stretch

    steps:
      - checkout

      - run:
          name: Install deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev g++ build-essential
            sudo pip3 install --upgrade setuptools pytz
            sudo pip3 install awsebcli==3.20.0

      - aws-cli/install
      - aws-cli/configure

      - run:
          name: npm build dash
          command: cd dash; npm install

      - run:
          name: deploy
          command: cd dash; npm run deploy-dev

      - run:
          name: invalidate CloudFront cache
          command: |
            aws cloudfront create-invalidation \
            --distribution-id E1IIPZGX1PO4X0 \
            --paths "/*"

workflows:
  version: 2
  build:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only:
                - master
      - deploy-dev:
          filters:
            branches:
              only:
                - dev
